version: '3'

services:
   logspout:
    image: bekt/logspout-logstash
    environment:
      ROUTE_URIS: 'logstash://10.10.174.101:5000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 30s



