---
- hosts: vms
  gather_facts: false
  become_user: root
  become: true

  vars_files:
    - ../group_vars/vars
    - ../group_vars/vault

  environment: "{{ env }}"

  tasks:
    - name: Clean Any Subscription Data
      shell:
        cmd: subscription-manager clean

    - name: Register now
      shell:
        cmd: subscription-manager register --org="{{rhn_orgid}}" --activationkey="{{rhn_key}}" 
        #cmd: subscription-manager register --username="{{redhat_user}}" --password="{{redhat_pass}}" --auto-attach
      register: res
