---
- hosts: docker
  gather_facts: false
  become_user: root
  become: true

  vars_files:
    - ../group_vars/vars

  environment: "{{ env }}"

  tasks:
    - name: Create partition on second disk
      parted:
        label: gpt
        part_type: primary
        device: "{{ disk2 }}"
        flags: [ lvm ]
        state: present
        number: 1
        part_start: 0%
        part_end: 100%
      ignore_errors: yes
        
    - name: Create Docker VG
      lvg:
        vg: docker
        pvs: "{{ disk2_part }}"

    - name: Create thinpool LV
      lvol:
        lv: thinpool
        opts: --wipesignatures y
        vg: docker
        size: 95%VG

    - name: Create thinpoolmeta LV
      lvol:
        lv: thinpoolmeta
        opts: --wipesignatures y
        vg: docker
        size: 1%VG

    - name: LV convert
      command: lvconvert -y  --zero n -c 512K  --thinpool docker/thinpool --poolmetadata docker/thinpoolmeta
      ignore_errors: yes

    - name: Config thinpool profile
      copy: src=../files/docker-thinpool.profile dest=/etc/lvm/profile/docker-thinpool.profile

    - name: LV change
      command: lvchange --metadataprofile docker-thinpool docker/thinpool
      ignore_errors: yes

    - name: LV monitor
      command: lvs -o+seg_monitor

    - name: Create /etc/docker directory
      file:
        path: /etc/docker
        state: directory

    - name: Config Docker daemon
      template: src=../templates/daemon.json.j2 dest=/etc/docker/daemon.json
