---
- hosts: docker,logger
  gather_facts: false
  become_user: root
  become: true

  vars_files:
    - ../group_vars/vars

  environment: "{{ env }}"

  tasks:
    - name: Open required ports for rsyslog
      command: firewall-cmd --permanent --zone=public --add-port=514/tcp --add-port=514/udp
      when: inventory_hostname in groups.logger

    - name: Reload firewalld configuration
      command: firewall-cmd --reload
      when: inventory_hostname in groups.logger

    - name: Install dependencies
      yum:
        name: rsyslog
        state: latest

    - name: Configure logger server
      copy: src=../files/rsyslog.conf dest=/etc/rsyslog.conf
      when: inventory_hostname in groups.logger
      notify: Restart Rsyslog

    - name: Allow docker nodes to send logs
      template: src=../templates/rsyslog.conf.j2 dest=/etc/rsyslog.conf
      when: inventory_hostname in groups.docker
      notify: Restart Rsyslog

  handlers:
    - name: Restart Rsyslog
      systemd:
        name: rsyslog
        state: restarted

