---
- hosts: worker
  gather_facts: false
  become_user: root
  become: true

  vars_files:
    - ../group_vars/vars

  environment: "{{ env }}"

  tasks:
    - name: Open required ports for Workers
      command: firewall-cmd --permanent --zone=public --add-port=443/tcp --add-port=2377/tcp --add-port=4789/tcp --add-port=4789/udp --add-port=7946/tcp --add-port=7946/udp --add-port=12376/tcp

    - name: Reload firewalld configuration
      command: firewall-cmd --reload

    - name: Get worker token
      include_vars:
        file: /tmp/worker_token
        name: add_worker

    - name: Check if node already belongs to the swarm
      shell: docker info | grep "Swarm{{':'}} inactive" | wc -l
      register: swarm_inactive

    - name: Add Worker nodes to the swarm
      command: "{{ add_worker.token }}"
      when: swarm_inactive.stdout == "1"
