---
- hosts: vms
  gather_facts: false
  connection: local
  become_user: root
  become: true

  vars_files:
    - ../group_vars/vars
    - ../group_vars/vault

  environment: "{{ env }}"
 
  tasks:
    - name: Power on guests
      vsphere_guest:
        vcenter_hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        guest: "{{ inventory_hostname }}"
        state: powered_on

    - name: Wait for VMs to boot up
      pause:
        minutes: 3
