---
- hosts: docker
  gather_facts: false
  become_user: root
  become: true

  vars_files:
    - ../group_vars/vars

  environment: "{{ env }}"

  tasks:
    - name: Enable and start docker service
      systemd:
        name: docker
        enabled: yes
        state: started
